### ISSUE TITLE
`choice` microstate toggle appears to be broken on `master` 

### ISSUE THREAD

**Issue by zigahertz** [cowboyd/ember-microstates#12]
I am using version 0.2.1 of your library in a project. In a feature branch, I am pulling `master` so that I can incorporate the updated code you added for https://github.com/cowboyd/ember-microstates/pull/10. 

When I use the latest version of this code - toggle of `choice` microstates no longer works. When I click on a selection, I get this message in the console: 
`Cannot read property 'map' of undefined` - which is coming from https://github.com/cowboyd/ember-microstates/blob/master/addon/models/choice.js#L22

I tried to replicate this in a couple of twiddles. Here's the working example with v0.2.1:
https://ember-twiddle.com/3a6e7fc92711d4aa956171f78d32721d

Here's the broken example, the only that has changed is that it is using `master`:
https://ember-twiddle.com/a1ba79430d687afb60efa162e26627da

This second twiddle doesn't actually run - it's just to show you the setup (it appears to be having a problem loading a dependency from Git that isn't a tagged version).

**Comment by cowboyd** [comment]
Thanks for reporting this @zigahertz. Does it work for you if you use this branch https://github.com/cowboyd/ember-microstates/tree/pure-javascript-microstate ?

**Comment by zigahertz** [comment]
@cowboyd thanks - that doesn't work, unfortunately - am getting the same `Cannot read property 'map' of undefined` error as before

**Comment by cowboyd** [comment]
@zigahertz I am so sorry about this, I didn't read your example more carefully. The latest version of microstates supports the ability to have full state transitions on "sub" objects, so the `toggle` action lives on the option object, not the choice (even though it will cause a new choice to be emitted).

In [this gist][1], what you want is to invoke `{{action pet.toggle}}` instead of `{{action pets.toggle pet}}`. By attaching the action to the context, it makes it easier to carry that context arround.

Notice how the `options` key is embedded in the `actions` hash https://github.com/cowboyd/ember-microstates/blob/master/addon/helpers/choice.js#L12-L22

If microstates sees an object in the actions hash instead of function, it will attach all the functions contained in that object to the sub-object of the microstate with the same key.

Again, my apologies for not reading carefully. I was so flummoxed by trying to track down what could possibly be going wrong that I forgot to check the usage.

[1]: https://gist.github.com/zigahertz/a1ba79430d687afb60efa162e26627da#file-templates-components-pet-selector-hbs-L10
